from __future__ import annotations
from dataclasses import dataclass
from typing import Dict, Any, Optional
import logging

from services.db_service.db_service import DbService

logger = logging.getLogger(__name__)


@dataclass
class TicketPayload:
    project_key: str
    issue_type: str
    summary: str
    description: str
    department: str
    primary_label: str
    processed_data_id: Optional[int] = None


class AbstractTicketClient:
    """
    Abstract interface for ticketing clients (mock Jira, real Jira, etc.).
    """

    def create_issue(self, payload: TicketPayload) -> Dict[str, Any]:
        raise NotImplementedError


class MockTicketClient(AbstractTicketClient):
    """
    Jira clone: stores tickets in the 'tickets' table via DbService.
    """

    def __init__(self, db: Optional[DbService] = None) -> None:
        self.db = db or DbService()

    def create_issue(self, payload: TicketPayload) -> Dict[str, Any]:
        fake_key = f"MOCK-{payload.project_key}-{payload.issue_type}"

        ticket_id = self.db.insert_ticket(
            processed_data_id=payload.processed_data_id,
            primary_label=payload.primary_label,
            department=payload.department,
            summary=payload.summary,
            description=payload.description,
            external_key=fake_key,
            source="mock",
            status="OPEN",
        )

        return {
            "id": ticket_id,
            "key": fake_key,
            "project_key": payload.project_key,
            "issue_type": payload.issue_type,
        }


class RealJiraTicketClient(AbstractTicketClient):
    """
    Real Jira integration: creates tickets in Atlassian Jira and stores references in local DB.
    """

    def __init__(self, db: Optional[DbService] = None) -> None:
        from packages.jira_client.client import JiraClient
        
        self.db = db or DbService()
        try:
            self.jira = JiraClient()
            logger.info("Initialized real Jira client")
        except Exception as e:
            logger.error(f"Failed to initialize Jira client: {e}")
            raise

    def create_issue(self, payload: TicketPayload) -> Dict[str, Any]:
        """
        Create issue in real Jira and store reference in local database.
        """
        try:
            # Build Jira description with structured feedback info
            jira_description = (
                f"*Label:* {payload.primary_label}\n"
                f"*Department:* {payload.department}\n\n"
                f"*Customer Feedback:*\n{payload.description}\n\n"
                f"---\n"
                f"_Auto-generated by FlightSense AI Classifier_"
            )
            
            # Create issue in Jira
            jira_response = self.jira.create_issue(
                project_key=payload.project_key,
                issue_type=payload.issue_type,
                summary=payload.summary,
                description=jira_description,
            )
            
            jira_key = jira_response.get("key")
            jira_id = jira_response.get("id")
            
            logger.info(f"Created Jira issue: {jira_key}")
            
            # Store ticket reference in local database
            ticket_id = self.db.insert_ticket(
                processed_data_id=payload.processed_data_id,
                primary_label=payload.primary_label,
                department=payload.department,
                summary=payload.summary,
                description=payload.description,
                external_key=jira_key,
                source="jira",
                status="OPEN",
            )
            
            return {
                "id": ticket_id,
                "key": jira_key,
                "jira_id": jira_id,
                "project_key": payload.project_key,
                "issue_type": payload.issue_type,
                "url": f"{self.jira.base_url}/browse/{jira_key}",
            }
            
        except Exception as e:
            logger.error(f"Failed to create Jira issue: {e}")
            # Fallback: store in local DB even if Jira fails
            ticket_id = self.db.insert_ticket(
                processed_data_id=payload.processed_data_id,
                primary_label=payload.primary_label,
                department=payload.department,
                summary=payload.summary,
                description=payload.description,
                external_key=f"FAILED-{payload.project_key}",
                source="jira_failed",
                status="ERROR",
            )
            raise
